"""Generate the backtrace's symbol table from the transcription itself.

Every transcribed routine already carries the address it came from, and
`reconstruct/tests/provenance.py` is the thing that reads those. So the names a
guest backtrace prints are not a list somebody maintains by hand - they are the
port's own provenance comments, and a routine that gets transcribed tomorrow
appears in tomorrow's backtraces without anyone doing anything.

Stubs are included and **marked**, because a backtrace that ends in one is the
most useful backtrace this program produces: it says the game reached something
the port knows about and has not read yet.

Addresses are image offsets. Overlay routines (`VM.OVL VGA:0x...`) are left out
- their addresses are not image offsets and the loader chooses their segment at
run time, so they are resolved by `native_bind_overlay` instead.

This file is the port's own tooling; it is not a transcription.
"""
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "reconstruct", "tests"))
import provenance


# The two overlay translation units. Their provenance reads `VM.OVL VGA:0x12fb`
# and `SX.OVL SPKR:0x0480`, and the address in it is an offset into a driver the
# loader places at run time - not an image offset. Left in, `vm_driver_init` at
# VGA:0x0000 would claim image offset 0 and put a confident wrong name on the
# lowest addresses in every backtrace. They are bound by native_bind_overlay.
OVERLAY_UNITS = ("vmovl_vga.c", "sxovl_spkr.c")


def collect_overlay():
    """The VGA driver's own routines, keyed by their offset into VM.OVL.

    A trap inside the driver is the most likely trap there is - the driver is
    what touches A000 and the VGA ports - and until now it printed "not a
    transcribed routine" for every one of them, because these addresses are
    not image offsets and the image table cannot hold them. The loader chooses
    the overlay's segment at run time; `native_bind_overlay` already reads it
    out of DGROUP, so the backtrace can subtract it and look here.

    SX.OVL is left out: it is a different overlay at a different segment, and
    one table indexed by "offset into an overlay" would answer confidently
    about the wrong one.
    """
    out = {}
    path = os.path.join(ROOT, "reconstruct", "vmovl_vga.c")
    transcribed, _ours, stubs, _bare, _internal = provenance.check(path)
    for name, addr in transcribed:
        out[int(addr, 16)] = (name, 0)
    for name, addr in stubs:
        out[int(addr, 16)] = (name, 1)
    return out


def collect():
    out = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "reconstruct", "*.c"))):
        if os.path.basename(path) in OVERLAY_UNITS:
            continue
        transcribed, _ours, stubs, _bare, _internal = provenance.check(path)
        for name, addr in transcribed:
            try:
                out[int(addr, 16)] = (name, 0)
            except ValueError:
                pass                      # an overlay address, not an image one
        for name, addr in stubs:
            try:
                out[int(addr, 16)] = (name, 1)
            except ValueError:
                pass
    return out


def main():
    syms = collect()
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "syms.c")
    with open(dst, "w") as f:
        f.write('/*\n'
                ' * GENERATED by tools/native/gensyms.py - do not edit.\n'
                ' *\n'
                ' * The port\'s provenance comments, as a table the backtrace can\n'
                ' * search. `stub` marks a routine whose address is known and whose\n'
                ' * body is not written yet.\n'
                ' */\n'
                '#include <stdint.h>\n\n'
                'const struct { uint32_t at; const char *name; uint8_t stub; }\n'
                'sym_table[] = {\n')
        for at in sorted(syms):
            name, stub = syms[at]
            f.write("    { 0x%05x, \"%s\", %d },\n" % (at, name, stub))
        f.write("};\n\n"
                "const int32_t sym_count = %d;\n" % len(syms))

    # The driver's symbols go in their own file, deliberately.
    #
    # They were in syms.c beside the image's, and the two are indistinguishable
    # once read: an overlay offset is a small number and so is a low image
    # offset. A script bounding a routine by "the next symbol" mixed them and
    # bounded step_machine at 0x00f86 by vm_bitmap_list_size at *overlay*
    # 0x00fd4, seventy-eight bytes in - which reported a routine with no return
    # instruction, a real thing this game has, so it read as a finding rather
    # than as a bug. Separate files cannot be mixed by accident.
    ovl = collect_overlay()
    odst = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "ovlsyms.c")
    with open(odst, "w") as f:
        f.write("/*\n"
                " * GENERATED by tools/native/gensyms.py - do not edit.\n"
                " *\n"
                " * The VGA driver, by offset into VM.OVL. **These are not image\n"
                " * offsets.** The loader picks the segment, so they are resolved\n"
                " * against the base the backtrace reads out of DGROUP. Anything\n"
                " * wanting image offsets wants syms.c, and mixing the two gives\n"
                " * a wrong answer that looks like a right one.\n"
                " */\n"
                "#include <stdint.h>\n\n"
                "const struct { uint32_t at; const char *name; uint8_t stub; }\n"
                "ovl_sym_table[] = {\n")
        for at in sorted(ovl):
            name, stub = ovl[at]
            f.write("    { 0x%05x, \"%s\", %d },\n" % (at, name, stub))
        f.write("};\n\n"
                "const int32_t ovl_sym_count = %d;\n" % len(ovl))

    n_stub = sum(1 for _n, s in syms.values() if s)
    print("wrote %s: %d routines, %d of them stubs; %s: %d in the VGA driver"
          % (os.path.relpath(dst, ROOT), len(syms), n_stub,
             os.path.relpath(odst, ROOT), len(ovl)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
