"""Generate one shim per dispatched routine, from the port's own prototypes.

A shim is what Borland would have compiled for the call: one parameter per word
the guest pushed, in the order it pushed them, converted to what the port's
function actually takes, and then the return simulated the way the routine's own
`ret` would have left the machine.

Doing it as typed C rather than as a table of widths is the point. The compiler
checks that a far pointer is two words and becomes a host pointer, that a `long`
is two words and becomes a `uint32_t`, and that the argument count matches the
prototype - none of which a descriptor string can check, and all of which have
been wrong here at least once.

The types come from `reconstruct/tim.h`, so a routine whose signature changes
regenerates rather than rots. `routines.def` says only *where* each routine is and how it is
called; everything else lives in the shim it generates.

This file is the port's own tooling; it is not a transcription.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.dirname(os.path.abspath(__file__))

# The registers each register-argument routine takes, in the port's own order.
# Read off the entries when those routines were specced; they are not uniform,
# which is why each has its own list.
REGS = {
    "poly_walk":              "es ax bx si bp cx di",
    "poly_edge_vertical":     "es bp si cx",
    "poly_edge_diagonal":     "es bx bp cx si",
    "poly_edge_steep":        "es bx bp cx si",
    "poly_edge_shallow_right":"es bx bp cx si",
    "poly_edge_shallow_left": "es bx bp cx si",
    "poly_outline":           "di si bp",
}


def prototypes():
    """name -> (return type, [parameter types]) from the port's header."""
    src = open(os.path.join(ROOT, "reconstruct", "tim.h")).read()
    out = {}
    for m in re.finditer(r'^([a-z_0-9]+)\s+(\w+)\(([^;]*?)\)\s*;', src, re.M | re.S):
        rt, name, args = m.group(1), m.group(2), m.group(3)
        args = " ".join(args.split())
        if args in ("void", ""):
            out[name] = (rt, [])
            continue
        out[name] = (rt, [a.strip() for a in args.split(",")])
    return out


def kind_of(param):
    """How many guest words this parameter is, and how to build it."""
    if "*" in param:
        return "p"
    if "int32" in param:
        return "l"
    return "w"


def emit(entries, protos):
    out = []
    w = out.append
    w('/*')
    w(' * GENERATED by tools/native/genshims.py - do not edit.')
    w(' *')
    w(' * One shim per dispatched routine: the call Borland would have compiled,')
    w(' * with the return simulated before control goes back to the emulator.')
    w(' * See the generator for why this is typed C rather than a table of widths.')
    w(' */')
    w('#include <stdint.h>')
    w('#include <stdio.h>')
    w('')
    w('#include "native.h"')
    w('#include "shim.h"')
    w('#include "../../reconstruct/dgroup.h"')
    w('#include "../../reconstruct/tim.h"')
    w('')

    for e in entries:
        name = e["fn"]
        rt, params = protos.get(name, (None, None))
        if rt is None:
            raise SystemExit("no prototype for %s" % name)

        w('static void sh_%s(call_t *c)' % name)
        w('{')
        if e["regs"]:
            regs = REGS[name].split()
            if len(regs) != len(params):
                raise SystemExit("%s: %d registers for %d parameters"
                                 % (name, len(regs), len(params)))
            for i, (r, p) in enumerate(zip(regs, params)):
                w('    uint16_t a%d = areg(c, UC_X86_REG_%s);' % (i, r.upper()))
        else:
            w('    %s_args(c);' % ("far" if e["far"] else "near"))
            if params:
                w('')
            for i, p in enumerate(params):
                k = kind_of(p)
                if k == "p":
                    w('    const uint8_t *a%d = aptr(c);' % i)
                elif k == "l":
                    w('    uint32_t a%d = alng(c);' % i)
                else:
                    w('    uint16_t a%d = aword(c);' % i)
        w('')

        call = "%s(%s)" % (name, ", ".join("a%d" % i for i in range(len(params))))
        far = "f" if e["far"] else "n"
        pops = e["pops"]
        if e["ret"] == "RET_NONE":
            w('    %s;' % call)
            w('    r%s_void(c, %d);' % (far, pops))
        elif e["ret"] == "RET_AX":
            w('    r%s_ax(c, (uint16_t)%s, %d);' % (far, call, pops))
        else:
            w('    r%s_dxax(c, (uint32_t)%s, %d);' % (far, call, pops))
        w('}')
        w('')

    w('/* The table dispatch.c walks: where each routine is, and its shim. */')
    w('const shim_entry shim_table[] = {')
    for e in entries:
        w('    { %#07x, "%s", sh_%s, %d },'
          % (e["at"], e["fn"], e["fn"], 1 if e["overlay"] else 0))
    w('};')
    w('')
    w('const int32_t shim_count = (int32_t)(sizeof shim_table /')
    w('                                     sizeof shim_table[0]);')
    return "\n".join(out) + "\n"


def parse_table():
    """The entries in routines.def, as data.

    Split on commas rather than matched positionally: a positional regex over
    four different macros is the kind of thing that silently drops an entry,
    and a dropped entry here is a routine the emulator quietly runs itself.
    """
    src = open(os.path.join(HERE, "routines.def")).read()
    out = []
    for m in re.finditer(r'\b(FAR_C|OVL_C|NEAR_P|REG_N)\s*\(([^)]*)\)', src):
        kind = m.group(1)
        f = [x.strip() for x in m.group(2).split(",")]
        # The file documents the macro forms in its own header, and a regex
        # over the whole file matches those too. Anything whose first field is
        # not an address is prose, not an entry.
        if not re.fullmatch(r'0x[0-9a-f]+', f[0]):
            continue
        at = int(f[0], 16)
        if kind in ("FAR_C", "OVL_C"):
            out.append(dict(at=at, far=1, overlay=(kind == "OVL_C"), pops=0,
                            regs=0, ret=f[2], fn=f[3]))
        elif kind == "NEAR_P":
            out.append(dict(at=at, far=0, overlay=0, pops=int(f[2]), regs=0,
                            ret=f[3], fn=f[4]))
        else:
            out.append(dict(at=at, far=0, overlay=0, pops=0, regs=1,
                            ret=f[3], fn=f[4]))
    return out


def main():
    entries = parse_table()
    # the two that already had shims are the port functions themselves
    for e in entries:
        e["fn"] = re.sub(r'^sh_', '', e["fn"])
    protos = prototypes()
    text = emit(entries, protos)
    dst = os.path.join(HERE, "shims.c")
    open(dst, "w").write(text)
    print("wrote %s: %d shims" % (os.path.relpath(dst, ROOT), len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
