/*
 * GENERATED by tools/native/genshims.py - do not edit.
 *
 * One shim per dispatched routine: the call Borland would have compiled,
 * with the return simulated before control goes back to the emulator.
 * See the generator for why this is typed C rather than a table of widths.
 */
#include <stdint.h>
#include <stdio.h>

#include "native.h"
#include "shim.h"
#include "../../reconstruct/dgroup.h"
#include "../../reconstruct/tim.h"

static void sh_dos_findfirst(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)dos_findfirst(a0, a1), 0);
}

static void sh_dos_findnext(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)dos_findnext(a0, a1), 0);
}

static void sh_dos_chdir(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)dos_chdir(a0), 0);
}

static void sh_dos_unlink(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)dos_unlink(a0), 0);
}

static void sh_dos_getdate(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    dos_getdate(a0);
    rf_void(c, 0);
}

static void sh_dos_isatty(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)dos_isatty(a0), 0);
}

static void sh_dos_lseek(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    rf_dxax(c, (uint32_t)dos_lseek(a0, a1, a2, a3), 0);
}

static void sh_dos_read(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)dos_read(a0, a1, a2), 0);
}

static void sh_dos_ioctl(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    rf_ax(c, (uint16_t)dos_ioctl(a0, a1, a2, a3), 0);
}

static void sh_dos_getattr(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)dos_getattr(a0, a1, a2), 0);
}

static void sh_dos_close(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)dos_close(a0), 0);
}

static void sh_dos_open_named(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)dos_open_named(a0, a1), 0);
}

static void sh_dos_get_cur_dir(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    dos_get_cur_dir(a0);
    rf_void(c, 0);
}

static void sh_dos_getvect(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_dxax(c, (uint32_t)dos_getvect(a0), 0);
}

static void sh_dos_setvect(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    dos_setvect(a0, a1, a2);
    rf_void(c, 0);
}

static void sh_dos_setdisk(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    dos_setdisk(a0);
    rf_void(c, 0);
}

static void sh_dos_write(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)dos_write(a0, a1, a2), 0);
}

static void sh_stdio_fclose(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)stdio_fclose(a0), 0);
}

static void sh_flush_stream(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)flush_stream(a0), 0);
}

static void sh_stdio_fopen(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)stdio_fopen(a0, a1), 0);
}

static void sh_stdio_fread(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    rf_ax(c, (uint16_t)stdio_fread(a0, a1, a2, a3), 0);
}

static void sh_stdio_fseek(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    rf_ax(c, (uint16_t)stdio_fseek(a0, a1, a2, a3), 0);
}

static void sh_stdio_fgetc(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)stdio_fgetc(a0), 0);
}

static void sh_dos_tell(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_dxax(c, (uint32_t)dos_tell(a0), 0);
}

static void sh_read_translated(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)read_translated(a0, a1, a2), 0);
}

static void sh_mouse_init(call_t *c)
{
    far_args(c);

    rf_ax(c, (uint16_t)mouse_init(), 0);
}

static void sh_mouse_set_speed(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    mouse_set_speed(a0);
    rf_void(c, 0);
}

static void sh_mouse_set_ranges(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    mouse_set_ranges(a0, a1, a2, a3);
    rf_void(c, 0);
}

static void sh_mouse_set_user_handler(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    mouse_set_user_handler(a0, a1);
    rf_void(c, 0);
}

static void sh_mouse_save_vga(call_t *c)
{
    far_args(c);

    mouse_save_vga();
    rf_void(c, 0);
}

static void sh_mouse_restore_vga(call_t *c)
{
    far_args(c);

    mouse_restore_vga();
    rf_void(c, 0);
}

static void sh_mouse_move_to(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)mouse_move_to(a0, a1), 0);
}

static void sh_install_keyboard(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    rf_ax(c, (uint16_t)install_keyboard(a0), 0);
}

static void sh_restore_write_mode(call_t *c)
{
    far_args(c);

    restore_write_mode();
    rf_void(c, 0);
}

static void sh_poly_walk(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_AX);
    uint16_t a2 = areg(c, UC_X86_REG_BX);
    uint16_t a3 = areg(c, UC_X86_REG_SI);
    uint16_t a4 = areg(c, UC_X86_REG_BP);
    uint16_t a5 = areg(c, UC_X86_REG_CX);
    uint16_t a6 = areg(c, UC_X86_REG_DI);

    poly_walk(a0, a1, a2, a3, a4, a5, a6);
    rn_void(c, 0);
}

static void sh_poly_edge_vertical(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_BP);
    uint16_t a2 = areg(c, UC_X86_REG_SI);
    uint16_t a3 = areg(c, UC_X86_REG_CX);

    poly_edge_vertical(a0, a1, a2, a3);
    rn_void(c, 0);
}

static void sh_poly_edge_diagonal(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_BP);
    uint16_t a3 = areg(c, UC_X86_REG_CX);
    uint16_t a4 = areg(c, UC_X86_REG_SI);

    poly_edge_diagonal(a0, a1, a2, a3, a4);
    rn_void(c, 0);
}

static void sh_poly_edge_steep(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_BP);
    uint16_t a3 = areg(c, UC_X86_REG_CX);
    uint16_t a4 = areg(c, UC_X86_REG_SI);

    poly_edge_steep(a0, a1, a2, a3, a4);
    rn_void(c, 0);
}

static void sh_poly_edge_shallow_right(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_BP);
    uint16_t a3 = areg(c, UC_X86_REG_CX);
    uint16_t a4 = areg(c, UC_X86_REG_SI);

    poly_edge_shallow_right(a0, a1, a2, a3, a4);
    rn_void(c, 0);
}

static void sh_poly_edge_shallow_left(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_BP);
    uint16_t a3 = areg(c, UC_X86_REG_CX);
    uint16_t a4 = areg(c, UC_X86_REG_SI);

    poly_edge_shallow_left(a0, a1, a2, a3, a4);
    rn_void(c, 0);
}

static void sh_poly_outline(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_DI);
    uint16_t a1 = areg(c, UC_X86_REG_SI);
    uint16_t a2 = areg(c, UC_X86_REG_BP);

    poly_outline(a0, a1, a2);
    rn_void(c, 0);
}

static void sh_clip_polygon(call_t *c)
{
    far_args(c);

    clip_polygon();
    rf_void(c, 0);
}

static void sh_vm_set_display_lines(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    vm_set_display_lines(a0);
    rf_void(c, 0);
}

static void sh_vm_init(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)vm_init(a0, a1, a2), 0);
}

static void sh_vm_driver_init(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)vm_driver_init(a0, a1, a2), 0);
}

static void sh_vm_reset_attributes(call_t *c)
{
    far_args(c);

    vm_reset_attributes();
    rf_void(c, 0);
}

static void sh_vm_nothing(call_t *c)
{
    far_args(c);

    vm_nothing();
    rf_void(c, 0);
}

static void sh_vm_span_dithered(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_AX);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_CX);
    uint16_t a3 = areg(c, UC_X86_REG_ES);
    uint16_t a4 = areg(c, UC_X86_REG_DI);

    vm_span_dithered(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_span(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_AX);
    uint16_t a1 = areg(c, UC_X86_REG_BX);
    uint16_t a2 = areg(c, UC_X86_REG_CX);
    uint16_t a3 = areg(c, UC_X86_REG_ES);
    uint16_t a4 = areg(c, UC_X86_REG_DI);

    vm_span(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_blit_scaled_row(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_AX);
    uint16_t a1 = areg(c, UC_X86_REG_BP);
    uint16_t a2 = areg(c, UC_X86_REG_DI);
    uint16_t a3 = areg(c, UC_X86_REG_ES);
    uint16_t a4 = areg(c, UC_X86_REG_DX);
    uint16_t a5 = areg(c, UC_X86_REG_CX);
    uint16_t a6 = areg(c, UC_X86_REG_SI);
    uint16_t a7 = areg(c, UC_X86_REG_DS);

    vm_blit_scaled_row(a0, a1, a2, a3, a4, a5, a6, a7);
    rf_void(c, 0);
}

static void sh_vm_blit_run(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_BX);
    uint16_t a1 = areg(c, UC_X86_REG_CX);
    const uint8_t *a2 = aregptr(c, UC_X86_REG_DS, UC_X86_REG_SI);
    uint16_t a3 = areg(c, UC_X86_REG_ES);
    uint16_t a4 = areg(c, UC_X86_REG_DI);
    uint32_t a5 = acarry(c);

    vm_blit_run(a0, a1, a2, a3, a4, a5);
    rf_void(c, 0);
}

static void sh_vm_draw_line(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_BX);
    uint16_t a1 = areg(c, UC_X86_REG_CX);
    uint16_t a2 = areg(c, UC_X86_REG_DX);
    uint16_t a3 = areg(c, UC_X86_REG_SI);

    vm_draw_line(a0, a1, a2, a3);
    rf_void(c, 0);
}

static void sh_vm_fill_spans(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_SI);

    vm_fill_spans(a0, a1);
    rf_void(c, 0);
}

static void sh_vm_set_palette(call_t *c)
{
    far_args(c);

    const uint8_t *a0 = aptr(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    vm_set_palette(a0, a1, a2);
    rf_void(c, 0);
}

static void sh_vm_load_palette(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    vm_load_palette(a0, a1);
    rf_void(c, 0);
}

static void sh_vm_blend_palette(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    vm_blend_palette(a0, a1, a2, a3);
    rf_void(c, 0);
}

static void sh_vm_bitmap_list_size(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_dxax(c, (uint32_t)vm_bitmap_list_size(a0, a1), 0);
}

static void sh_vm_load_bitmap_list(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);

    vm_load_bitmap_list(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_chunky_to_planar(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);

    vm_chunky_to_planar(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_read_four_planes(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);

    vm_read_four_planes(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_build_mask_plane(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);

    vm_build_mask_plane(a0, a1, a2, a3, a4);
    rf_void(c, 0);
}

static void sh_vm_blit_glyph(call_t *c)
{
    uint16_t a0 = areg(c, UC_X86_REG_ES);
    uint16_t a1 = areg(c, UC_X86_REG_SI);
    uint16_t a2 = areg(c, UC_X86_REG_AX);
    uint16_t a3 = areg(c, UC_X86_REG_BX);
    uint16_t a4 = areg(c, UC_X86_REG_DX);
    uint16_t a5 = areg(c, UC_X86_REG_BP);

    vm_blit_glyph(a0, a1, a2, a3, a4, a5);
    rf_void(c, 0);
}

static void sh_vm_save_rect(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);
    uint16_t a5 = aword(c);

    vm_save_rect(a0, a1, a2, a3, a4, a5);
    rf_void(c, 0);
}

static void sh_vm_buffer_size(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_dxax(c, (uint32_t)vm_buffer_size(a0, a1), 0);
}

static void sh_vm_restore_rect(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);
    uint16_t a5 = aword(c);

    vm_restore_rect(a0, a1, a2, a3, a4, a5);
    rf_void(c, 0);
}

static void sh_vm_read_pixel(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rf_ax(c, (uint16_t)vm_read_pixel(a0, a1), 0);
}

static void sh_vm_plot_pixel(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);

    rf_ax(c, (uint16_t)vm_plot_pixel(a0, a1, a2), 0);
}

static void sh_vm_show_page(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);

    vm_show_page(a0);
    rf_void(c, 0);
}

static void sh_vm_copy_rect(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    vm_copy_rect(a0, a1, a2, a3);
    rf_void(c, 0);
}

static void sh_vm_blit_rows(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);
    uint16_t a4 = aword(c);
    uint16_t a5 = aword(c);

    vm_blit_rows(a0, a1, a2, a3, a4, a5);
    rf_void(c, 0);
}

static void sh_vm_blit_bitmap(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    vm_blit_bitmap(a0, a1, a2, a3);
    rf_void(c, 0);
}

static void sh_dos_alloc_bytes(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);
    uint16_t a2 = aword(c);
    uint16_t a3 = aword(c);

    rf_dxax(c, (uint32_t)dos_alloc_bytes(a0, a1, a2, a3), 0);
}

static void sh_dos_free_far(call_t *c)
{
    far_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    dos_free_far(a0, a1);
    rf_void(c, 0);
}

static void sh_dos_creat(call_t *c)
{
    near_args(c);

    uint16_t a0 = aword(c);
    uint16_t a1 = aword(c);

    rn_ax(c, (uint16_t)dos_creat(a0, a1), 4);
}

static void sh_dos_truncate(call_t *c)
{
    near_args(c);

    uint16_t a0 = aword(c);

    dos_truncate(a0);
    rn_void(c, 2);
}

/* The table dispatch.c walks: where each routine is, and its shim. */
const shim_entry shim_table[] = {
    { 0x0b6b7, "dos_findfirst", sh_dos_findfirst, 0 },
    { 0x0b6d3, "dos_findnext", sh_dos_findnext, 0 },
    { 0x0b755, "dos_chdir", sh_dos_chdir, 0 },
    { 0x0b794, "dos_unlink", sh_dos_unlink, 0 },
    { 0x0bd4a, "dos_getdate", sh_dos_getdate, 0 },
    { 0x0c018, "dos_isatty", sh_dos_isatty, 0 },
    { 0x0c0c3, "dos_lseek", sh_dos_lseek, 0 },
    { 0x0c185, "dos_read", sh_dos_read, 0 },
    { 0x0c8a3, "dos_ioctl", sh_dos_ioctl, 0 },
    { 0x0cd3d, "dos_getattr", sh_dos_getattr, 0 },
    { 0x0cd80, "dos_close", sh_dos_close, 0 },
    { 0x0d707, "dos_open_named", sh_dos_open_named, 0 },
    { 0x0b7b3, "dos_get_cur_dir", sh_dos_get_cur_dir, 0 },
    { 0x0bd70, "dos_getvect", sh_dos_getvect, 0 },
    { 0x0bd7f, "dos_setvect", sh_dos_setvect, 0 },
    { 0x0b819, "dos_setdisk", sh_dos_setdisk, 0 },
    { 0x0df7a, "dos_write", sh_dos_write, 0 },
    { 0x0ce15, "stdio_fclose", sh_stdio_fclose, 0 },
    { 0x0ce92, "flush_stream", sh_flush_stream, 0 },
    { 0x0d0ce, "stdio_fopen", sh_stdio_fopen, 0 },
    { 0x0d1c4, "stdio_fread", sh_stdio_fread, 0 },
    { 0x0d26c, "stdio_fseek", sh_stdio_fseek, 0 },
    { 0x0d404, "stdio_fgetc", sh_stdio_fgetc, 0 },
    { 0x0c27b, "dos_tell", sh_dos_tell, 0 },
    { 0x0da6d, "read_translated", sh_read_translated, 0 },
    { 0x21f1d, "mouse_init", sh_mouse_init, 0 },
    { 0x0b859, "mouse_set_speed", sh_mouse_set_speed, 0 },
    { 0x21f8d, "mouse_set_ranges", sh_mouse_set_ranges, 0 },
    { 0x21fbe, "mouse_set_user_handler", sh_mouse_set_user_handler, 0 },
    { 0x2200f, "mouse_save_vga", sh_mouse_save_vga, 0 },
    { 0x22074, "mouse_restore_vga", sh_mouse_restore_vga, 0 },
    { 0x22113, "mouse_move_to", sh_mouse_move_to, 0 },
    { 0x21094, "install_keyboard", sh_install_keyboard, 0 },
    { 0x1e94c, "restore_write_mode", sh_restore_write_mode, 0 },
    { 0x1f562, "poly_walk", sh_poly_walk, 0 },
    { 0x1f265, "poly_edge_vertical", sh_poly_edge_vertical, 0 },
    { 0x1f3bf, "poly_edge_diagonal", sh_poly_edge_diagonal, 0 },
    { 0x1f281, "poly_edge_steep", sh_poly_edge_steep, 0 },
    { 0x1f3e6, "poly_edge_shallow_right", sh_poly_edge_shallow_right, 0 },
    { 0x1f4a1, "poly_edge_shallow_left", sh_poly_edge_shallow_left, 0 },
    { 0x1f219, "poly_outline", sh_poly_outline, 0 },
    { 0x20c07, "clip_polygon", sh_clip_polygon, 0 },
    { 0x08f77, "vm_set_display_lines", sh_vm_set_display_lines, 0 },
    { 0x22483, "vm_init", sh_vm_init, 0 },
    { 0x00000, "vm_driver_init", sh_vm_driver_init, 1 },
    { 0x0011d, "vm_reset_attributes", sh_vm_reset_attributes, 1 },
    { 0x00252, "vm_nothing", sh_vm_nothing, 1 },
    { 0x0027a, "vm_span_dithered", sh_vm_span_dithered, 1 },
    { 0x0034f, "vm_span", sh_vm_span, 1 },
    { 0x003db, "vm_blit_scaled_row", sh_vm_blit_scaled_row, 1 },
    { 0x00938, "vm_blit_run", sh_vm_blit_run, 1 },
    { 0x00998, "vm_draw_line", sh_vm_draw_line, 1 },
    { 0x00be6, "vm_fill_spans", sh_vm_fill_spans, 1 },
    { 0x00ec1, "vm_set_palette", sh_vm_set_palette, 1 },
    { 0x00f15, "vm_load_palette", sh_vm_load_palette, 1 },
    { 0x00f57, "vm_blend_palette", sh_vm_blend_palette, 1 },
    { 0x00fd4, "vm_bitmap_list_size", sh_vm_bitmap_list_size, 1 },
    { 0x01015, "vm_load_bitmap_list", sh_vm_load_bitmap_list, 1 },
    { 0x010b8, "vm_chunky_to_planar", sh_vm_chunky_to_planar, 1 },
    { 0x011bb, "vm_read_four_planes", sh_vm_read_four_planes, 1 },
    { 0x011ee, "vm_build_mask_plane", sh_vm_build_mask_plane, 1 },
    { 0x0124b, "vm_blit_glyph", sh_vm_blit_glyph, 1 },
    { 0x012fb, "vm_save_rect", sh_vm_save_rect, 1 },
    { 0x0138e, "vm_buffer_size", sh_vm_buffer_size, 1 },
    { 0x013b9, "vm_restore_rect", sh_vm_restore_rect, 1 },
    { 0x01453, "vm_read_pixel", sh_vm_read_pixel, 1 },
    { 0x014c9, "vm_plot_pixel", sh_vm_plot_pixel, 1 },
    { 0x0150f, "vm_show_page", sh_vm_show_page, 1 },
    { 0x01561, "vm_copy_rect", sh_vm_copy_rect, 1 },
    { 0x015d0, "vm_blit_rows", sh_vm_blit_rows, 1 },
    { 0x01707, "vm_blit_bitmap", sh_vm_blit_bitmap, 1 },
    { 0x21abd, "dos_alloc_bytes", sh_dos_alloc_bytes, 0 },
    { 0x21b34, "dos_free_far", sh_dos_free_far, 0 },
    { 0x0d584, "dos_creat", sh_dos_creat, 0 },
    { 0x0d59d, "dos_truncate", sh_dos_truncate, 0 },
};

const int32_t shim_count = (int32_t)(sizeof shim_table /
                                     sizeof shim_table[0]);
